spring:
  config:
    import: "aws-parameterstore:/config/application_prod/"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  team-name: ${info.team-name:DefaultTeam}

cloud:
  aws:
    s3:
      bucket: odin-s3-cloud-bucket
    region:
      static: ap-northeast-2