spring:
  config:
    import: "aws-parameterstore:/config/application_prod/"
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

info:
  team-name: ${info.team-name:DefaultTeam}